name: inventario-vacunacion-empleados

services:
  db:
    image: postgres:14-alpine
    container_name: vacunacion_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vacunacion_db
      POSTGRES_USER: ${DB_USER:-alefiengo}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-alefiengo}
    volumes:
      - vacunacion_data:/var/lib/postgresql/data

volumes:
  vacunacion_data:
